Document: daq2-clean
Title: Debian daq2-clean Manual
Author: <insert document author here>
Abstract: This manual describes what daq2-clean is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/daq2-clean/daq2-clean.sgml.gz

Format: postscript
Files: /usr/share/doc/daq2-clean/daq2-clean.ps.gz

Format: text
Files: /usr/share/doc/daq2-clean/daq2-clean.text.gz

Format: HTML
Index: /usr/share/doc/daq2-clean/html/index.html
Files: /usr/share/doc/daq2-clean/html/*.html
